### PR TITLE
Create harbour-determinant-es.ts

### PR DESCRIPTION
**Pull request by carlosgonz0**

### CODE REVIEW

**Comment by carlosgonz0** [comment]
Thank you

**Comment by R1tschY** [comment]
In the next days 0.2 will be released. Please take a look at the 3 missing translations soon, to get it into the release.

**Comment by R1tschY** [comment]
Sorry for the late merging. I just forgot about it.

**Comment by carlosgonz0** [comment]
I am ready to get v0.2 right now on my fish device. : )

**Pull request merged**
